### ISSUE TITLE
Dúvida - get_ine_data com dimensões

### ISSUE THREAD

**Issue by rafabelokurows** [c-matos/ineptR#1]
Olá. 
Primeiramente, obrigado por este desenvolvimento, faz com que seja muito mais fácil obter dados do INE :)

``` r
library(ineptR)
df = get_ine_data("0002739")
head(df)
#>         dim_1 geocod                     geodsg dim_3 dim_3_t dim_4
#> 1 1997 / 1998     30 Região Autónoma da Madeira     1       H    11
#> 2 1997 / 1998    300 Região Autónoma da Madeira     1       H    11
#> 3 1997 / 1998     PT                   Portugal     1       H    11
#> 4 1997 / 1998      1                 Continente     1       H    11
#> 5 1997 / 1998     11                      Norte     1       H    11
#> 6 1997 / 1998    111                 Alto Minho     1       H    11
#>         dim_4_t valor sinal_conv            sinal_conv_desc
#> 1 Universitário   675       <NA>                       <NA>
#> 2 Universitário   675       <NA>                       <NA>
#> 3 Universitário 69520       <NA>                       <NA>
#> 4 Universitário 67782       <NA>                       <NA>
#> 5 Universitário 20466       <NA>                       <NA>
#> 6 Universitário  <NA>          - Dado nulo ou não aplicável
```

No entanto, tenho uma dúvida:
Como faço para informar algumas dimensões como parâmetros na chamada da função "get_ine_data".
Por exemplo, para este indicador:
https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_indicadores&indOcorrCod=0002739&selTab=tab0

Se eu quisesse obter somente dados para os sistemas de ensino universitário, ou seja, dimensão 4, códigos 11 e 21
![image](https://github.com/c-matos/ineptR/assets/55976107/a6d28869-67f5-4741-a8c9-eb4d116b9465)

E para alguns anos em particular, exemplo:
![image](https://github.com/c-matos/ineptR/assets/55976107/3303ebd0-e35f-4185-b102-4c277c459276)

Como ficaria a chamada da função?

Obrigado desde já!

**Comment by c-matos** [comment]
Boa tarde,

vou escrever uma vignette a detalhar melhor o processo (quando tiver disponibilidade...)
Neste caso concreto, de acordo com a imagem creio que na 1ª situação seria:
`df = get_ine_data("0002739", dim4 = c("11", "21"))`
Na 2ª situação seria:
`df = get_ine_data("0002739", dim1 = c("7A2022_3","7A2021_3","7A2020_3"))`
também é possível combinar ambos os cenários:
`df = get_ine_data("0002739", dim4 = c("11", "21"), dim1 = c("7A2022_3","7A2021_3","7A2020_3"))`

**Comment by rafabelokurows** [comment]
Obrigado pela resposta! Testei e funcionou perfeitamente com este formato de chamada!
